language: node_js
node_js:
 - "10"
 - "8"
install: npm ci

script: echo "Running tests against $(node -v)..."

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: npm test && cat ./coverage/lcov.info | coveralls && rm -rf ./coverage

cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.cache"
# script: 
#  - npm test
#  - kill $(jobs -p) || true
 
