language: node_js
node_js:
 - "10"
 - "8"
install: npm ci



cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.cache"
script: 
 - npm run test:cov && cat ./coverage/lcov.info | coveralls && rm -rf ./coverage
 - kill $(jobs -p) || true
 
